on:
  push:
    tags:
      - 'mac-v*.*.*'

name: Bundle Application for MacOS

jobs:
  build-mac:
    
    strategy:
      matrix:
        os: [macos-14]
        include:
          - os: macos-14
            dmg_file_name: Waveform-Wizard_macos-14.dmg
          # - os: ubuntu-22.04
          #   dmg_file_name: Waveform-Wizard_macos-13.deb

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Save version info
      run: |
        echo "meta_info = { 'version': '${{ github.ref_name }}' }" > src/main/python/version.py

    - name: temp
      run: ls -l /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ppg/installer/mac/create-dmg

    - name: Grant execute permissions for create-dmg
      run: chmod +x /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ppg/installer/mac/create-dmg/create-dmg

    - name: temp-2
      run: ls -l /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ppg/installer/mac/create-dmg

    - name: Freeze Application
      run: |
        ppg freeze

    - name: converting create-dmg file
      run: sed -i '' 's/\r$//' /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ppg/installer/mac/create-dmg/create-dmg

    - name: temp-3
      run: ls -la /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ppg/installer/mac/create-dmg/create-dmg

    - name: temp-4
      run: file /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ppg/installer/mac/create-dmg/create-dmg

    - name: Create Installer
      run: |
        ppg installer
        mv target/Waveform-Wizard.dmg target/${{ matrix.dmg_file_name }}
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        token: ${{ secrets.RELEASE_TOKEN }}
        files: |
          target/${{ matrix.dmg_file_name }}
